#ifndef SERVER_HTTP_VERSION_H_
#define SERVER_HTTP_VERSION_H_

#define MRT_HTTP_VERSION_STRING "1.1"
#define MRT_HTTP_VERSION 11
#define MRT_HTTP_VERSION_MAJOR 1
#define MRT_HTTP_VERSION_MINOR 1
#define MTR_HTTP_VERSION_PATCH 0

#endif
